# The numpy.random package

# Explain the overall purpose of the package
***
Numpy is the go-to package for computation in Python. It is a Python library that multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.




In [86]:
# Import packages that will be used
import numpy as np
import matplotlib.pyplot as plt

# Explain the use of the “Simple random data” and “Permutations” functions
***
Ther are two permutations functions: "shuffle" and "permutation". The shuffle function mixes the array along the first axis of a multi-dimensional array. The parameter passed in is the array, list or mutable sequence to be shuffled. [1] For multi-demensional arrays, the order of the sub arrays are changed but the elements inside remain the same. The permutation function mixes the elements inside an array randomly. If an integer (x) is passed into the function, it will return a shuffled range up to but not including x.






In [87]:
# Create and array 'arr' 
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Example of shuffle function

In [88]:
# Shuffle the array 
np.random.shuffle(arr)
arr

array([2, 1, 0, 3, 9, 4, 6, 5, 8, 7])

In [89]:
# Reshape the array 
newarr = arr.reshape(5,2)
newarr

array([[2, 1],
       [0, 3],
       [9, 4],
       [6, 5],
       [8, 7]])

In [90]:
# Shuffle the newly arranged array
np.random.shuffle(arr)
arr

array([6, 1, 5, 0, 2, 8, 3, 4, 7, 9])

We can see that the elements in each array remain the same, but the positions of each sub array is randomized (shuffled)

## Example of permutations function

In [91]:
# Randomly arrange a sequence up to 10
np.random.permutation(10)

array([7, 4, 2, 1, 6, 0, 5, 8, 3, 9])

In [92]:
# Randomly arrange the array I created
np.random.permutation(arr)

array([2, 6, 7, 4, 1, 9, 0, 5, 8, 3])

In [93]:
np.random.permutation(newarr)
newarr

array([[6, 1],
       [5, 0],
       [2, 8],
       [3, 4],
       [7, 9]])

# Explain the use and purpose of at least five “Distributions” functions
***


# Explain the use of seeds in generating pseudorandom numbers
***


A pseudorandom number generator is an algorithm that uses mathematical formulas to create sequences of random numbers. The numbers produced are an approximation of, but not true random numbers.

# References 
***
[1] https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html