# The numpy.random package

# Explain the overall purpose of the package
***
Numpy is the go-to package for computation in Python. It is a Python library that multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.




In [53]:
# Import packages that will be used
import numpy as np
import matplotlib.pyplot as plt

# Explain the use of the “Simple random data” and “Permutations” functions
***








## Simple random data

A simple random sample is a randomly selected group of a population. Each member of the population has an equal chance of being selected. 

**random.Generator.integers**

This function returns random integers in a given range and shape. The shape refers to how many numbers are outputted, and in what groups. It returns integers from the “discrete uniform” distribution of the specified dtype. [2] dtype or "Data type objects" refers to how the bytes that make up array objects should be interpreted i.e if they are an integer, float, how many bytes in the number etc. [3]

**Example**

In [65]:
# Generate 10 random integers up to (but not including) 5.
rng.integers(5, size = 10)

array([3, 2, 4, 0, 2, 0, 0, 3, 4, 1], dtype=int64)

In [68]:
# Generate 10 random integers in a 2 x 5 array, up to but not including 20.
rng.integers(20, size= (2, 5))

array([[13,  7, 10,  3, 18],
       [11, 13, 14,  2,  6]], dtype=int64)

In [72]:
# Generate a 1 x 3 array with different lower bounds for each integer and a higher bound of 20
rng.integers([3, 5, 10], 20)

array([12,  7, 16], dtype=int64)

In [74]:
# Generate a 1 x 4 array, with a lower bound of 2 and different higher bounds.
rng.integers(2, [3, 7, 15, 10])

array([2, 6, 7, 2], dtype=int64)

**random.Generator.random**

This function returns random floats in the half-open interval [0.0, 1.0)



A half-open interval is an interval in which one endpoint is included but not the other. In this case, it means greater than or equal to 0 and less than 1. [4]

In [75]:
rng.random()

0.9607242476699271

## Permutations functions 
There are two permutations functions: "shuffle" and "permutation". The shuffle function mixes the array along the first axis of a multi-dimensional array. The parameter passed in is the array, list or mutable sequence to be shuffled. [1] For multi-demensional arrays, the order of the sub arrays are changed but the elements inside remain the same. The permutation function mixes the elements inside an array randomly. If an integer (x) is passed into the function, it will return a shuffled range up to but not including x.

In [54]:
# Create and array 'arr'
rng = np.random.default_rng()
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Example of shuffle function

In [55]:
# Shuffle the array 
rng.shuffle(arr)
arr

array([2, 4, 5, 1, 3, 8, 0, 6, 7, 9])

In [56]:
# Reshape the array 
newarr = arr.reshape(5,2)
newarr

array([[2, 4],
       [5, 1],
       [3, 8],
       [0, 6],
       [7, 9]])

In [57]:
# Shuffle the newly arranged array
np.random.shuffle(arr)
arr

array([1, 8, 7, 4, 5, 6, 2, 9, 3, 0])

We can see that the elements in each array remain the same, but the positions of each sub array is randomized (shuffled)

## Example of permutations function

In [58]:
# Randomly arrange a sequence up to 10
rng = np.random.default_rng()
rng.permutation(10)


array([1, 3, 8, 2, 0, 7, 4, 9, 5, 6])

In [59]:
# Randomly arrange the array I created earlier
rng.permutation(arr)

array([1, 3, 9, 4, 2, 7, 5, 8, 0, 6])

In [60]:
rng.permutation(newarr)
newarr

array([[1, 8],
       [7, 4],
       [5, 6],
       [2, 9],
       [3, 0]])

# Explain the use and purpose of at least five “Distributions” functions
***


# Explain the use of seeds in generating pseudorandom numbers
***


A pseudorandom number generator is an algorithm that uses mathematical formulas to create sequences of random numbers. The numbers produced are an approximation of, but not true random numbers.

# References 
***
[1] https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html

[2] https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers

[3] https://numpy.org/doc/stable/reference/arrays.dtypes.html

[4] https://mathworld.wolfram.com/Half-ClosedInterval.html